import { useState, useRef } from "react";
import { Camera, BadgeCheck, Award, Loader2, User } from "lucide-react";
import { profileApi } from "~/api/profileApi";
import { pengajuanApi } from "~/api/pengajuan";
import { Toast } from "~/components/ui/toast";
import { cn } from "~/lib/utils";
import { useAuth } from "~/hooks/useAuth";

interface ProfileHeaderProps {
    profile: any;
    onUpdate: () => void;
}

export function ProfileHeader({ profile, onUpdate }: ProfileHeaderProps) {
    const { user } = useAuth();
    const [uploading, setUploading] = useState(false);
    const [toastProps, setToastProps] = useState<{title: string, variant?: "success" | "destructive"} | null>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handlePhotoClick = () => {
        if (!uploading) fileInputRef.current?.click();
    };

    const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        if (!file.type.startsWith("image/")) {
            setToastProps({ title: "File harus berupa gambar", variant: "destructive" });
            return;
        }

        if (file.size > 5 * 1024 * 1024) {
            setToastProps({ title: "Ukuran gambar maksimal 5MB", variant: "destructive" });
            return;
        }

        setUploading(true);
        try {
            await pengajuanApi.updateProfile({ photo: file });
            
            // Update local user in localStorage so chat sidebar reflects the change immediately
            const savedUser = localStorage.getItem("user");
            if (savedUser) {
                const user = JSON.parse(savedUser);
                // We don't have the exact filename here, but onUpdate() will trigger a refetch of the profile
                // which will eventually sync everything. For immediate UI feedback in other components:
                // Note: The specific filename is generated by backend, so we might need to be careful.
                // However, the chat fetches contacts/history which will now include the photo.
            }
            
            setToastProps({ title: "Foto profil berhasil diperbarui", variant: "success" });
            onUpdate();
        } catch (error: any) {
            setToastProps({ title: error.message || "Gagal memperbarui foto profil", variant: "destructive" });
        } finally {
            setUploading(false);
            if (fileInputRef.current) fileInputRef.current.value = "";
        }
    };

    const displayNama = profile?.nama || user?.name || "";
    const studentInitials = displayNama 
        ? displayNama.split(' ').map((n: string) => n[0]).join('').substring(0, 2).toUpperCase()
        : 'M';

    return (
        <div className="relative">
            {toastProps && (
                <div className="fixed top-4 right-4 z-[100]">
                    <Toast title={toastProps.title} variant={toastProps.variant} onClose={() => setToastProps(null)} />
                </div>
            )}
            
            {/* Header Background Cover */}
            <div className="h-48 md:h-64 rounded-3xl relative overflow-hidden bg-gray-900 border border-gray-100">
                <img 
                    src="/images/Banner_Universitas_Pancasila.png" 
                    alt="University Banner" 
                    className="absolute inset-0 w-full h-full object-cover opacity-70"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/10 to-transparent" />
            </div>
            
            {/* Profile Info Overlay */}
            <div className="px-6 md:px-12 -mt-20 md:-mt-24 pb-8 flex flex-col md:flex-row items-center md:items-end gap-6 text-center md:text-left">
                <div className="relative group shrink-0">
                    <div 
                        className="w-40 h-40 md:w-48 md:h-48 rounded-[2.5rem] border-8 border-white bg-white shadow-xl overflow-hidden relative cursor-pointer"
                        onClick={handlePhotoClick}
                    >
                        {profile?.photo ? (
                            <img 
                                src={profileApi.getProfilePhotoUrl(profile.photo)} 
                                alt={displayNama}
                                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                            />
                        ) : (
                            <div className="w-full h-full flex items-center justify-center bg-gray-100 text-[#119DA4] font-black text-4xl">
                                {studentInitials}
                            </div>
                        )}
                        
                        {uploading ? (
                            <div className="absolute inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center">
                                <Loader2 className="w-8 h-8 text-white animate-spin" />
                            </div>
                        ) : (
                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all flex items-center justify-center">
                                <Camera className="w-10 h-10 text-white opacity-0 group-hover:opacity-100 transition-opacity" />
                            </div>
                        )}
                    </div>
                    <p className="mt-3 text-[10px] font-bold text-gray-400 bg-white/50 backdrop-blur-sm px-3 py-1 rounded-full border border-white shadow-sm inline-block">
                        Rekomendasi: Rasio 1:1, Max 5MB
                    </p>
                    <input type="file" className="hidden" ref={fileInputRef} onChange={handleFileChange} accept="image/*" />
                </div>

                <div className="flex-1 min-w-0 pb-2">
                    <h1 className="text-3xl md:text-4xl font-black text-gray-900 drop-shadow-sm">{displayNama || "..."}</h1>
                    <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 mt-3">
                        <div className="flex items-center gap-2 bg-white/80 backdrop-blur-md px-4 py-2 rounded-2xl border border-white shadow-sm">
                            <BadgeCheck className="w-5 h-5 text-[#119DA4]" />
                            <span className="font-bold text-gray-700">{profile?.nim || "-"}</span>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    );
}
